macos_option_as_alt true
copy_on_select yes
confirm_os_window_close 0
font_family JetBrainsMono Nerd Font Mono
clipboard_control write-clipboard write-primary read-clipboard read-primary

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME


# letters
map ctrl+shift+p>w kitten hints --program "@" --type regex --regex "[a-zA-Z]+" 
map ctrl+shift+p>l kitten hints --program "@" --type regex --regex ".*"

# absolute path
# map ctrl+shift+p>a kitten hints --program "@" --type regex --regex "(/|~/)([^/ ]+/?)*$"
# map ctrl+shift+p>a kitten hints --program "@" --type regex --regex "~?/[^\s]+"
map ctrl+shift+p>a kitten hints --program "@" --type regex --regex '(?:^|\s|:|`|'\''|")(~?/[^\s:"`'\'']+)'
#map ctrl+shift+p>c kitten hints --program "@" --type regex --regex '(?:^|\s|:|`|'\''|")(~?/[^\s:"`'\'']+:[0-9]+)'
map ctrl+shift+p>c kitten hints --program "@" --type regex --regex '(?:^|\s|:|`|"|'\''|│)(~?/[^\s:"`'\'']+:[0-9]+)'



# line suffix
map ctrl+shift+p>x kitten hints --program "@" --type regex --regex "\\b\\S.*"
# snake case
map ctrl+shift+p>s kitten hints --program "@" --type regex --regex "[a-zA-Z_]+" 
# vim word
map ctrl+shift+p>v kitten hints --program "@" --type regex --regex "[a-zA-Z0-9_]+" 
# numbers
map ctrl+shift+p>n kitten hints --program "@" --type regex --regex "[0-9]+"
# big word
map ctrl+shift+p>z kitten hints --program "@" --type regex --regex '[|│]?(\S+)'
map ctrl+shift+p>p kitten hints --program "-" --type regex --regex '[|│]?(\S+)'
# map ctrl+shift+p>p kitten hints --program "-" --type regex --regex "\\S+"
# map ctrl+shift+p>w kitten hints --program "@" --type word

map ctrl+j send_key down
map ctrl+k send_key up




# pagers
# scrollback_pager nvim
# scrollback_pager     $SHELL -c "sed -e 's/\s*.*$//' -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba' -e '}' | sed 's/\s*$//g' | nvim -c 'setlocal nomodifiable ft=man nonumber nolist showtabline=0 foldcolumn=0' -c 'autocmd VimEnter * normal G' +KittyBufferHistoryClean - "

# suffix
map ctrl+shift+p>x kitten word_to_eol.py
# Add this to your kitty.conf temporarily
# map ctrl+shift+p>x kitten hints --type word --program "echo 'KITTEN CALLED' >> /tmp/test.log"

map ctrl+shift+u kitten hints --customize-processing ~/.config/kitty/hints_auto_open_single_url.py

